audio-display=no
autocreate-playlist=filter
border=no
cache-on-disk=no
msg-module=yes
osc=no
osd-bar-align-y=1
osd-bar-border-size=0
osd-bar-h=0.300000
osd-bar-w=100
osd-border-size=2
save-position-on-quit=yes
scale=ewa_lanczos
screenshot-format=avif
screenshot-template="%x/shots/%F - [%P]v%#02n"
sid=no
stop-screensaver=yes
sub-ass-force-margins=yes
sub-ass-justify=yes
sub-file-paths=zzz_subtitles:sub:subtitles:subs
sub-justify=left
sub-use-margins=yes
term-osd-bar=yes
term-osd-bar-chars=└─• 🕭
title=${media-title} - mpv player
video-align-y=-1
volume-max=700
ytdl-raw-options=yes-playlist=

[linux]
input-ipc-server=/tmp/mpv-socket
profile-cond=p.platform=="linux"
term-title=${media-title} - mpv ${?pause==yes:paused }

[android]
profile-cond=p.platform=="android"
video=no

[remove film grain]
profile-cond=(p.filename=="watership down (1978).mp4" or p.filename=="anna karenina (1935).mp4" or p.filename=="the matrix (1999).mp4" or p.filename=="serenity (2005).mkv")
vf=hqdn3d

[windows]
force-window=yes
keep-open=yes
profile-cond=p.platform=="windows"
