data: ENC[AES256_GCM,data:PIFkKbRBar7MTivsN7GNDG1nPzE3Qnwr8etkAV4U2CS/TFRkPtjeFeQ=,iv:ZhJVXyzswqMGLpYwKIztmwA9FUP3lORqksr/ZJUgMWI=,tag:f5WB+5qynwGBJZxgVP0CEg==,type:str]
sops:
    age:
        - recipient: age1cfyx7eu9jdr6klvlhtpmuxuspg9gn02lvn22vqpyx0yz0dxjld9qpqh2rq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSnp4bjlKTk81ODB1L0tu
            RUJnM2EzckFLUkZ6ME1PYTlnTzRFdDJkSXhrClhYeHNtNlQva3p6S05vb0phdVRj
            VFpkNTZiUlo3MG56YmJsQ2ZBZklpRVEKLS0tIHpmSEI4allVQjh4bFk1c2lxS3hE
            T1VEU3dCUm56NWdYczlHNVJIbXVzZ3MKrULsbfGv17Aw22MtzvhmDurWd+fvAvf8
            lXza37EeUpgqYtk6g8UIhZ86z4U7zGLF7ert6aJigfFgNLp0okoOPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-01T21:19:44Z"
    mac: ENC[AES256_GCM,data:UAELkONA7e6bFMP5RWZr88mkYymJ1qCvZ1fqAKC2XTkMM9I5gnsNy/szeYIzIA8qVENhjOkbcutB3okvsM4RKGA9g42Rdpz21KmcNrbV5QmwxTojJJolTNcIr4o9FJMv8rKHZNIMLOxmQuxu9bhP1ugnm8XJifdu/hm9UVKJenk=,iv:Oky1GAaX4nvDKMIJbvg6ji8DLK9lSDrhilftoc56A8w=,tag:0E2oGPdOytpy6IdoV5zIeg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
